-- 코드를 작성해주세요
SELECT ID,
    CASE NTILE_RANK
        WHEN 4 THEN 'CRITICAL'
        WHEN 3 THEN 'HIGH'
        WHEN 2 THEN 'MEDIUM'
        WHEN 1 THEN 'LOW'
    END AS COLONY_NAME
FROM(
    SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY) AS NTILE_RANK FROM ECOLI_DATA
) AS RANKED
ORDER BY ID ASC;