-- 코드를 작성해주세요
select I.ITEM_ID, I.ITEM_NAME, I.RARITY
from ITEM_TREE T
join ITEM_INFO I
ON T.ITEM_ID = I.ITEM_ID
WHERE T.PARENT_ITEM_ID IN (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
ORDER BY I.ITEM_ID DESC;